### ISSUE TITLE
make this package available on PyPI

### ISSUE THREAD

**Issue by jannikmi** [casus/minterpy#2]
It would be great if I could just call `pip install minterpy` or to specify `minterpy` of a pinned version as a regular dependency in a requirements file.
For that this package needs to be uploaded to [PyPI](https://pypi.org/).

**Comment by DanielKotik** [comment]
I feel responsible for this and would setup the corresponding CI/CD pipeline, but suggest to do this only when there is a stable (major) release available. I am in touch with @szabo137 on this. As long as there is no stable release, publishing on TestPyPI is meaningful, in order to check if the distribution can be  build and packed.

**Comment by jannikmi** [comment]
Sounds good.

**Comment by szabo137** [comment]
The registration on PyPi will be part of the beta release, which we are currently working on. This will be combined with several other things like building and deployment of the documentation. So, please stay tuned 😉

**Comment by szabo137** [comment]
I know, this issue was open for oversee ten months, but finally, you can download [version 0.2.0-alpha](https://github.com/casus/minterpy/releases/tag/v0.2.0-alpha) using 

```bash
pip install minterpy
```

Therefore, this issue is closed.
